title: Huichao Xie's Homepage
page-top-title: Huichao Xie
top-section-bg-text: Be what you wanna be
home-subtitle: Huichao Xie&ensp;|&ensp;谢惠超
copyright-text: '&copy; Huichao Xie 2023-2025. All Rights Reserved.'
